const fs = require('fs');
const path = require('path');

// Path to the template file
const templatePath = path.join(__dirname, 'sidebars.template.js');
// Path to the actual sidebars.js file
const sidebarPath = path.join(__dirname, 'sidebars.js');

// Read the template file
fs.readFile(templatePath, 'utf8', (err, data) => {
    if (err) {
        console.error('Error reading the template file:', err);
        return;
    }

    const date = new Date()
    var header = `// This file was generated by a script. Do not edit this file manually.\n`;
    header += `// Last update on ${date.toISOString().replace('T', ' ').substring(0, 19)} UTC\n\n`;

    // Replace the placeholder with the current datetime
    const updatedData = data.replace('yyyy.mm.dd HH:ii', date.toISOString().replace('T', ' ').substring(0, 16));

    // Write the updated content to sidebars.js
    fs.writeFile(sidebarPath, header + updatedData, 'utf8', (err) => {
        if (err) {
            console.error('Error writing the updated sidebars.js file:', err);
        } else {
            console.log('sidebars.js updated successfully with the current datetime.');
        }
    });
});
